language: node_js
node_js: stable

sudo: false

install: true  # yarn bug

os:
  - linux
#  - osx

branches:
  only: master

notifications:
  email:
    recipients:
      - alanmacgowan@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

cache:
  directories: node_modules

before_script:
  - npm i -g npm@^5.3.0 && npm --version
  - npm install
  - npm install -g firebase-tools
  
script:
  - npm run build

after_success:
  - firebase deploy --non-interactive --token $FIREBASE_TOKEN
  
after_failure:
  - cat /home/travis/build/alanmacgowan/BookLibrary.Angular/npm-debug.log

