language: node_js
node_js: stable

sudo: false

install: true  # yarn bug

os:
  - linux
#  - osx

before_script:
  - npm i -g npm@^5.3.0 && npm --version
  - npm install

after_failure:
  - cat /home/travis/build/alanmacgowan/BookLibrary.Angular/npm-debug.log

branches:
  only: master

notifications:
  email:
    recipients:
      - alanmacgowan@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

cache:
  directories: node_modules

script:
  - npm run build

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $pagestoken
#   on:
#     branch: master